#!/bin/bash

# Store the current working directory path in the variable 'p'
p=$PWD

# Loop through each directory inside the current working directory
for d in $p/*; do
    # Change to the current directory in the loop
    cd "$d" || exit

    # Uncomment the line below if you need to convert nucleotide sequences in 'armfinder_forinterpro.fa' 
    # to amino acid sequences and save the output in 'amrfinder_forinterpro.faa'
    # transeq -sequence armfinder_forinterpro.fa -outseq amrfinder_forinterpro.faa &&

    # Remove sequences from 'amrfinder_forinterpro.faa' that match the specified pattern ('*') 
    # and save the remaining sequences in 'antibiotic_inactivation_corr.faa'
    seqkit grep --by-seq --invert-match --pattern '*' amrfinder_forinterpro.faa > antibiotic_inactivation_corr.faa

    # Use InterProScan to analyse the protein sequences in 'antibiotic_inactivation_corr.faa', 
    # save the results in the current directory, and include Gene Ontology (GO) terms
    /home/gomathinayagam/interproscan-5.65-97.0-64-bit/interproscan-5.65-97.0/./interproscan.sh -i antibiotic_inactivation_corr.faa -d . -goterms

    # Go back to the parent directory after processing the current one
    cd ..
done

# Remove underscores from the headers generated by CARD-RGI in the output file
# The following 'awk' command is designed to trim trailing characters (e.g., underscores) from each line of input
# awk '{ print substr( $0, 1, length($0)-2 ) }'

